/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;


import Clientes.InFr_GestionarCliente;
import Clientes.InFr_BuscarCliente;
import Clientes.ListaCliente;

import Empleados.InFr_GestionarEmpleado;
import Empleados.InFr_BuscarEmpleado;
import Empleados.Listaempleados;


import Vehiculos.InFr_GestionarVehiculo;
import Vehiculos.InFr_BuscarVehiculo;







/**
 *
 * @author UTN
 */
public class FrmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    private Listaempleados Listaempleados;
    private ListaCliente ListaCliente;
    public FrmMenu() {
        initComponents();
         Listaempleados = new Listaempleados();
         ListaCliente = new ListaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMIT_Ag_Cliente = new javax.swing.JMenuItem();
        jMIT_Bu_Cliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIT_Ag_Vehiculo = new javax.swing.JMenuItem();
        jMIT_Bu_Vehiculo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIT_Ag_Empleado = new javax.swing.JMenuItem();
        jMIT_Bu_Empleado = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMIT_Ag_Reserva = new javax.swing.JMenuItem();
        jMIT_Bu_Reserva = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("house");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        jMIT_Ag_Cliente.setText("Agregar");
        jMIT_Ag_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_Ag_ClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMIT_Ag_Cliente);

        jMIT_Bu_Cliente.setText("Buscar");
        jMIT_Bu_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_Bu_ClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMIT_Bu_Cliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vehiculos ");

        jMIT_Ag_Vehiculo.setText("Agregar");
        jMIT_Ag_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_Ag_VehiculoActionPerformed(evt);
            }
        });
        jMenu3.add(jMIT_Ag_Vehiculo);

        jMIT_Bu_Vehiculo.setText("Buscar");
        jMIT_Bu_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_Bu_VehiculoActionPerformed(evt);
            }
        });
        jMenu3.add(jMIT_Bu_Vehiculo);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Empleados");

        jMIT_Ag_Empleado.setText("Agregar");
        jMIT_Ag_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_Ag_EmpleadoActionPerformed(evt);
            }
        });
        jMenu4.add(jMIT_Ag_Empleado);

        jMIT_Bu_Empleado.setText("Buscar");
        jMIT_Bu_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_Bu_EmpleadoActionPerformed(evt);
            }
        });
        jMenu4.add(jMIT_Bu_Empleado);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reservas");

        jMIT_Ag_Reserva.setText("Agregar");
        jMenu5.add(jMIT_Ag_Reserva);

        jMIT_Bu_Reserva.setText("Buscar");
        jMenu5.add(jMIT_Bu_Reserva);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Contratos");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIT_Ag_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_Ag_ClienteActionPerformed
    InFr_GestionarCliente a = new InFr_GestionarCliente(ListaCliente);
    this.jDesktopPane1.add(a);
    a.setVisible(true);
    }//GEN-LAST:event_jMIT_Ag_ClienteActionPerformed

    private void jMIT_Bu_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_Bu_ClienteActionPerformed
    InFr_BuscarCliente c = new InFr_BuscarCliente();
    this.jDesktopPane1.add(c);
    c.setVisible(true);
    }//GEN-LAST:event_jMIT_Bu_ClienteActionPerformed

    private void jMIT_Bu_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_Bu_VehiculoActionPerformed
     InFr_BuscarVehiculo c = new InFr_BuscarVehiculo();
    this.jDesktopPane1.add(c);
    c.setVisible(true);     
    }//GEN-LAST:event_jMIT_Bu_VehiculoActionPerformed

    private void jMIT_Ag_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_Ag_VehiculoActionPerformed
       InFr_GestionarVehiculo v = new InFr_GestionarVehiculo();
    this.jDesktopPane1.add(v);
    v.setVisible(true);        
    }//GEN-LAST:event_jMIT_Ag_VehiculoActionPerformed

    private void jMIT_Ag_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_Ag_EmpleadoActionPerformed
   InFr_GestionarEmpleado empleadoFrame = new InFr_GestionarEmpleado(Listaempleados);
    jDesktopPane1.add(empleadoFrame);
    empleadoFrame.setVisible(true);
    empleadoFrame.toFront();
    }//GEN-LAST:event_jMIT_Ag_EmpleadoActionPerformed

    private void jMIT_Bu_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_Bu_EmpleadoActionPerformed
        InFr_BuscarEmpleado c = new InFr_BuscarEmpleado();
    this.jDesktopPane1.add(c);
    c.setVisible(true);
    }//GEN-LAST:event_jMIT_Bu_EmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMIT_Ag_Cliente;
    private javax.swing.JMenuItem jMIT_Ag_Empleado;
    private javax.swing.JMenuItem jMIT_Ag_Reserva;
    private javax.swing.JMenuItem jMIT_Ag_Vehiculo;
    private javax.swing.JMenuItem jMIT_Bu_Cliente;
    private javax.swing.JMenuItem jMIT_Bu_Empleado;
    private javax.swing.JMenuItem jMIT_Bu_Reserva;
    private javax.swing.JMenuItem jMIT_Bu_Vehiculo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
